name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Ambil Kode dari Repository
      uses: actions/checkout@v3

    - name: Siapkan Java (JDK 11)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Beri Izin pada File Gradle
      run: chmod +x ./gradlew

    - name: Build APK Debug
      run: ./gradlew assembleDebug

    - name: Upload APK sebagai Artefak
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
